- hosts: jboss_eap_rhel_hosts
  remote_user: "{{ ansible_rhel_user }}"
  sudo: true
  gather_facts: true

  vars_prompt:
  - name: "rhn_username"
    prompt: "Enter Your Red Hat Customer Portal Username"
    private: no

  - name: "rhn_password"
    prompt: "Enter Your Red Hat Customer Portal Password"
    private: yes

  roles:
  - jboss_common
  - jboss_eap

  tasks:
  - name: install web app
    get_url: 
      url: https://github.com/kenthua/kitchensink-war/blob/master/deployments/ROOT.war?raw=true
      dest: "{{ jboss_eap_home }}/standalone/deployments/jboss-kitchensink.war"
    